package com.lucky.collegemanagement.model

data class Student(
    val onlineQuizExamInfo: String = "",
    val onlineWrittenExamInfo: String = "",
    val password: String = "",
    val phoneNumber: String = "",
    val practiceSchoolInfo: String = "",
    val profileEmail: String = "",
    val regdNo: String = "",
    val resultInfo: String = "",
    val roomNumber: String = "",
    val section: String = "",
    val sic: String = "",
    val subjects: String = "",
    val timeTableLink: String = "",
    val holidaysTotal: String = "",
    val holidaysYear: String = "",
    val hostelName: String = "",
    val hostelRegistrationDate: String = "",
    val libraryBooks: String = "",
    val libraryReturnToday: String = "",
    val libraryReturnWeek: String = "",
    val lowAttendance: String = "",
    val name: String = "",
    val officialMailEmail: String = "",
    val officialMailId: String = "",
    val officialMailPassword: String = "",
    val examScheduleTomorrow: String = "",
    val facultyAdvisorName: String = "",
    val facultyAdvisorPhoneNumber: String = "",
    val feedbackEnd: String = "",
    val feedbackStart: String = "",
    val gender: String = "",
    val highAttendance: String = "",
    val holidaysList: List<String> = emptyList()
)
